# Generated by Django 5.2.1 on 2025-06-09 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo_image',
            field=models.ImageField(blank=True, default='', upload_to='portfolio/portfolio_image/%d/%m/%Y/'),
        ),
    ]
