# Generated by Django 5.2.1 on 2025-06-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_photos_category_alter_photos_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
