# Generated by Django 5.2.1 on 2025-07-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_photos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nome',
            field=models.CharField(max_length=65, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='descricao',
            field=models.CharField(max_length=165, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='historia',
            field=models.TextField(verbose_name='História'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='photo_image',
            field=models.ImageField(blank=True, default='', upload_to='portfolio/portfolio_image/%d/%m/%Y/', verbose_name='Trabalho'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='titulo',
            field=models.CharField(max_length=65, verbose_name='Título'),
        ),
    ]
